app:
  version: 1.0

server:
  port: 8081
#  servlet:
#    context-path: /system

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8070/eureka/
#
spring:
##
  application:
    name: system
## mysql 配置
  datasource:
    url: jdbc:mysql://172.18.36.120:3306/cms?characterEncoding=UTF-8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
## Redis 配置
  redis:
    host: 172.18.36.120
    port: 6379

mybatis:
  mapper-locations: classpath:mapper/*.xml
#  config-location: classpath:mybatis/mybatis-config.xml
#  configuration:
#    interceptors:
#      - com.su.system.interceptor.mybatis.SqlFetchInterceptor


#
logging:
  level:
    com.su: debug
#logging.level.org.springframework.transaction=debug
    org.mybatis: debug


