# 应用配置
app:
  version: 1.0   # 系统当前版本号
  aopLogOpen: 1   # 是否开启aop日志 0关闭，1开启
  ioEncryptOpen: 0  # 是否开启输入输出加密 0关闭，1开启
  aesKey: 123   # aes加密key

auth:
  excludes: login,logout,static,captcha   # 不做授权校验的URL

#server.port=8080
#server:
#  servlet:
#    context-path: /admin

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8070/eureka/

## Redis 配置
## Redis数据库索引（默认为0）
# spring.redis.database=0
## Redis服务器地址
spring:
  redis:
#    host: 172.18.36.120
    host: localhost
    port: 6379
  application:
    name: admin
#    password:


#
logging:
  level:
    com.su: debug
  file: /var/log/java/admin.log
